# Generated by Django 2.2.6 on 2019-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=1000)),
                ('image_date', models.DateField()),
                ('image_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
