# Generated by Django 2.2.6 on 2019-10-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_date',
            field=models.DateTimeField(),
        ),
    ]
