# Generated by Django 2.2.6 on 2019-10-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20191008_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDerivModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=1000)),
                ('image_date', models.DateTimeField()),
                ('image_url', models.CharField(max_length=1000)),
                ('image_deriv_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.ImageModel')),
            ],
        ),
    ]
