# Generated by Django 2.2.6 on 2019-10-08 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_imagederivmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagederivmodel',
            name='deriv_type',
            field=models.CharField(default=datetime.datetime(2019, 10, 8, 16, 26, 55, 505736, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
